services:
  postgresdb:
    image: 'postgres:alpine'
    container_name: postgres
    env_file: .env
    environment:
      - 'POSTGRES_DB=$POSTGRESDB_DATABASE'
      - 'POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD'
      - 'POSTGRES_USER=$POSTGRESDB_USER'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/${POSTGRESDB_DATABASE}'
    depends_on:
      - postgresdb
    volumes:
      - .:/app:rw
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'

volumes:
  postgres_data:

